travis:
  secure:
    BINSTAR_TOKEN: OdCzwzrfgDMRSlPbpJcIGbPQcSHpzus9NgBe1KYDD1wYJPaqjuyDNrA0OxIh8JjQ6gY6/2mX63G165oCsF6Eobguc57754lIL5Cv67GHYELQ5M21aBm1iBiob3Q7yKRE1Jim6G+ojE+gugRs1n8Yud+/5McCJ+z+1UCrtJdP3nSe+munlw428iggQIoD6y1nomPNP5wdNWR2DDY73jqiPbykx+fVYZPGpnaUWvOb3+JFlMwZZg/UNLJYrJIhTxJ11fkDLqEOj9hEtTfvoEu66Mwacg/THJGOdbhlKS4Zgk2vxgSZ/O+yt/d9t990hYRiHWh0/KfbCn4pNVvQGHUCyl+KBauockYHX4V+BDlz94nDpBmvKB6HdGc4+40fyF7kxVCr7hs9qwY4cfM8Gq0gMNt/kH08k/6a60Oxsg15cQtkk1NidiPLOkW7RRbOnQAc4rUO73c/qHOrVdcQH7Vkbqd8nFFMekFMqEbmWnTbz6Xr078ggkAHSnIEvfqZ5COlrEY6UzU1846L7RcrLKIqbvrR2VcJtl4HQEJM09/7MwBcjR8STOFOtLSZEjeinB5oEhgCqxumn/hdJZ1U1dlYjyYHrunELaOUb65JNpmJRsvID2TIH0Y3SG9+VQzJ1oDvvmk67+Ys3qppgvycpU9s+Q1BCDVIj+8T4nF8o1+811I=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
